### ISSUE TITLE
While setting up a local development server a cookie related error might occur

### ISSUE THREAD

**Issue by marceloFA** [euphwes/cubers.io#131]
Following the instructions at the [contributing guide](https://github.com/euphwes/cubers.io/blob/master/contributing.md) , everything works flawlessly, until I fired up the local development server for the first time. Flask throws `` TypeError: key: expected bytes or bytearray, but got 'NoneType' ``.

Checking the traceback this seems to be caused by the ``flask_login`` package when it is called under the hoods at this line:

``` 
File "/home/marcelo/cubers.io/app/routes/home/home_routes.py", line 19, in index
  if not current_user.is_authenticated:
```

It seems that ``flask_login `` tries to generate an HMAC code for the user and the above error is thrown at the browser. One last line from the traceback can confirm this:

```
File "/home/marcelo/.local/lib/python3.8/site-packages/flask_login/utils.py", line 343, in _cookie_digest
  return hmac.new(key, payload.encode('utf-8'), sha512).hexdigest()
```

The solution was to access the localhost using the browser in incognito mode.

It seems that if we previously logged in at https://cubers.io and the web browser saved cookies from the production server they somehow stop us from running the development server at the same browser? I'm not certain about the situation, and these are just my guesses, please let me know if I did anything wrong or if this is just how it works in flask development or even if this is just a matter of something I set up wrong at my local machine. Chrome is my browser.

**Comment by marceloFA** [comment]
I completed the whole setup, including virtualenv, requirements installation, node and the less package, db upgrade, the huey queue, and Reddit API key and secret as env variables.
As I solved this using incognito mode I'm not being stopped by this. I decided to open the issue just because some other new contributors might encounter the same scenario.

The complete traceback: 

```
(venv) marcelo@desktop:~/cubers.io$ flask run
 * Environment: development
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 244-789-923
Can't set up admin notifications: missing one or more of the following environment variables -- PUSHBULLET_API_KEY, PUSHBULLET_TARGET_CHANNEL
Can't set up admin notifications: missing one or more of the following environment variables -- PUSHBULLET_API_KEY, PUSHBULLET_TARGET_CHANNEL
127.0.0.1 - - [06/Oct/2020 13:53:42] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/marcelo/.local/lib/python3.8/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/marcelo/.local/lib/python3.8/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/marcelo/.local/lib/python3.8/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/marcelo/.local/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/marcelo/.local/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/marcelo/.local/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/marcelo/.local/lib/python3.8/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/marcelo/.local/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/marcelo/.local/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/marcelo/.local/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/marcelo/cubers.io/app/routes/home/home_routes.py", line 19, in index
    if not current_user.is_authenticated:
  File "/home/marcelo/.local/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/marcelo/.local/lib/python3.8/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/home/marcelo/.local/lib/python3.8/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/home/marcelo/.local/lib/python3.8/site-packages/flask_login/utils.py", line 335, in _get_user
    current_app.login_manager._load_user()
  File "/home/marcelo/.local/lib/python3.8/site-packages/flask_login/login_manager.py", line 353, in _load_user
    return self._load_from_cookie(request.cookies[cookie_name])
  File "/home/marcelo/.local/lib/python3.8/site-packages/flask_login/login_manager.py", line 387, in _load_from_cookie
    user_id = decode_cookie(cookie)
  File "/home/marcelo/.local/lib/python3.8/site-packages/flask_login/utils.py", line 55, in decode_cookie
    if safe_str_cmp(_cookie_digest(payload), digest):
  File "/home/marcelo/.local/lib/python3.8/site-packages/flask_login/utils.py", line 343, in _cookie_digest
    return hmac.new(key, payload.encode('utf-8'), sha512).hexdigest()
  File "/usr/lib/python3.8/hmac.py", line 153, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib/python3.8/hmac.py", line 48, in __init__
    raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
TypeError: key: expected bytes or bytearray, but got 'NoneType'
127.0.0.1 - - [06/Oct/2020 13:53:42] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [06/Oct/2020 13:53:43] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [06/Oct/2020 13:53:43] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [06/Oct/2020 13:53:43] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [06/Oct/2020 13:53:43] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [06/Oct/2020 13:53:44] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -

```

**Comment by euphwes** [comment]
Do you have your secret key defined? From `config.py`:

`    FLASK_SECRET_KEY = environ.get('FLASK_SECRET_KEY')`

This needs to exist in your environment variables (or you can *temporarily* replace this line in the config with a hardcoded value). This secret key is used when signing cookies. Though I'm not sure why incognito mode would make a difference...

**Comment by marceloFA** [comment]
Thank you for digging into this! I didn't have a FLASK_SECRET_KEY. Now that I set up one everything works fine!!

**Comment by euphwes** [comment]
Great! Yeah please do, looks like you identified a gap in that readme! I figured I probably didn't catch everything, and at this point it's probably slightly outdated.
